# Generated by Django 5.1.1 on 2024-10-02 18:54

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100)),
                ('userage', models.PositiveIntegerField()),
                ('usergender', models.CharField(max_length=10)),
                ('useremail', models.EmailField(max_length=255, unique=True)),
                ('usercontact', models.CharField(max_length=15, unique=True)),
                ('guardiancontact', models.CharField(max_length=15)),
                ('userpassword', models.CharField(default='password', max_length=255)),
            ],
        ),
    ]
