# Generated by Django 5.1.1 on 2024-10-05 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userAuth', '0002_rename_userage_user_age_rename_useremail_user_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_staff',
        ),
    ]
